社員新規登録の採番方法の見直し

diff --git a/APPLI/EMPLOYEE/NEW/CGI/COMPLETE b/APPLI/EMPLOYEE/NEW/CGI/COMPLETE
--- a/APPLI/EMPLOYEE/NEW/CGI/COMPLETE
+++ b/APPLI/EMPLOYEE/NEW/CGI/COMPLETE
@@ -36,6 +36,38 @@ FIN
 	exit 1
 }
 
+########################################
+#EMPOLYEEのデータ操作をロック
+LOCK=`${SYSD}/CGI/LOCK/LOCK 'EMPLOYEE'`
+LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
+
+########################################
+#社員番号の次のロットを追加する
+if [ ${LOCK_STATUS} = 'LOCKED' ]; then
+    LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
+    START=$((LATEST_NUM + 1))
+    END=$((START + 3))
+    SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ ${START} ${END} 'EMPLOYEE' `
+fi
+
+########################################
+#社員番号ロット追加の一連処理でのエラー処理
+if [ ${LOCK_STATUS} != 'LOCKED'] || [ ${SEQ_STATUS} = 'ERROR' ] || [ ${UNLOCK_STATUS} = 'ERROR']; then
+    cat ${SYSD}/HTML/ERROR/SYSTEM_ERROR.HTML                        |
+    sed -e "s/###ERROR1_LABEL###/新規社員登録処理中にエラー/"       |
+    sed -e "s/###ERROR2_LABEL###/処理ステータス:${STATUS}/"         |
+    sed -e "s/###ERROR3_LABEL###//"                                 > $tmp-html
+    exit 1
+fi
+
+########################################
+#EMPOLYEEのデータ操作ロックを解除
+UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK 'EMPLOYEE'`
+
+########################################
+#新規の社員番号を確定する
+EMPLOYEE_NUM=`${SYSD}/CGI/NUMBERS 'EMPLOYEE' `
+
 #######################################
 #Get Form Data
 VALUE1=$(nameread FAMILY_NAME $tmp-post)
@@ -44,10 +76,6 @@ VALUE3=$(nameread EMAIL $tmp-post)
 VALUE4=$(nameread PASSWORD $tmp-post)
 #VALUE5=$(nameread ADMIN_FLAG $tmp-post)
 VALUE5=0
-
-########################################
-#新規の社員番号を確定する
-EMPLOYEE_NUM=`${SYSD}/CGI/NUMBERS 'EMPLOYEES' `
 
 ########################################
 #Set DATE
